# Generated by Django 5.2.10 on 2026-01-26 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barista_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualorder",
            name="doser_number",
            field=models.IntegerField(
                default=1,
                help_text="Doser number (1-4)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="manualorder",
            name="dose_grams",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="manualorder",
            name="grind_grade",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(11),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="manualorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("ack", "Acknowledged"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
