# Generated by Django 5.2.10 on 2026-01-31 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barista_app", "0002_add_doser_and_int_dose"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualorder",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("machine", "Machine API")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="manualorder",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manual_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="manualorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("ack", "Acknowledged"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
