# Generated by Django 5.2.10 on 2026-01-31 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("barista_app", "0003_add_queue_and_source_to_manualorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="manualorder",
            name="external_order_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External order ID from the calling system",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="manualorder",
            name="order_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Recipe/order name from the calling system",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="dose_grams",
            field=models.IntegerField(
                default=18,
                help_text="Default dose in grams for this recipe",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="doser_number",
            field=models.IntegerField(
                default=1,
                help_text="Doser number to use (1-4)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="grind_grade",
            field=models.IntegerField(
                default=5,
                help_text="Default grind grade (1-11)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(11),
                ],
            ),
        ),
    ]
