# Generated by Django 4.2.28 on 2026-02-15 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barista_app', '0004_add_recipe_params_and_external_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualorder',
            name='grinder_number',
            field=models.IntegerField(default=1, help_text='Grinder number (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='manualorder',
            name='dose_grams',
            field=models.IntegerField(default=18, help_text='Auto-resolved from Recipe', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='manualorder',
            name='grind_grade',
            field=models.IntegerField(default=5, help_text='Auto-resolved from Recipe', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='ip_address',
            field=models.CharField(default='192.168.1.240', max_length=45),
        ),
    ]
