# Generated by Django 4.2.28 on 2026-02-15 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barista_app', '0005_manualorder_grinder_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='grinder_number',
            field=models.IntegerField(default=1, help_text='Grinder number to use (1-4)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
