# Generated by Django 4.2.28 on 2026-02-16 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barista_app', '0006_add_grinder_number_to_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('waiting_for_cup', 'Waiting for Cup'), ('sent', 'Sent'), ('ack', 'Acknowledged'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
